### ISSUE TITLE
TLB prefetcher

### ISSUE THREAD

**Issue by szuhzw** [agusnt/Berti-Artifact#6]
Hello. Does your project provide an interface for the TLB prefetcher?   
![图片](https://github.com/agusnt/Berti-Artifact/assets/65290731/17a37807-5077-4ddd-a062-e64b8e1eb8e2)

**Comment by agusnt** [comment]
Hello.

Yes, you can implement prefetcher as any other prefetcher.

**Comment by szuhzw** [comment]
Thank you.
